import React, {useState} from 'react';
import './busboard';
import {busInfo, getBusPredictions} from "./busboard";
import './sitewide.css';

async function getBuses(postcode: string): Promise<busInfo[][]> {
  // very basic testing string, you'll likely return a list of strings or JSON objects instead!
  //const postcodeString = (postcode === "") ? "" : ` - given postcode is ${postcode}`;
  //return "Some cool bus HTML generated by TypeScript" + postcodeString;
  console.log('getBuses started');
  return await getBusPredictions(postcode);
}

function App(): React.ReactElement {
  const [postcode, setPostcode] = useState<string>("");
  const [tableData, setTableData] = useState<busInfo[][]>([]);

  async function formHandler(event: React.FormEvent<HTMLFormElement>): Promise<void> {
    event.preventDefault(); // to stop the form refreshing the page when it submits
    const busInfoArray = await getBuses(postcode);
    setTableData(busInfoArray);
  }

  function createTD(arrivalInfo: busInfo): HTMLTableRowElement {
    let tableEntry = document.createElement('tr');
    tableEntry.innerHTML = "<td>" + arrivalInfo.lineName + "</td><td>" +
        arrivalInfo.destination + "</td><td>" + arrivalInfo.timeToArrival + "</td>";
    return tableEntry;
  }
  function populateBusTimetable() {
    console.log(tableData);
    let tableContainer = document.getElementById("tableContainer");
    if (tableContainer === null) {
      return;
    }
    tableContainer.innerHTML = "";
    tableData.forEach((busStopArrivalInfo)=>{
      const timetable = document.createElement('table');
      timetable.className = "centred";
      tableContainer?.appendChild(timetable);
      timetable.innerHTML = "";
      const timeTableHeader = document.createElement('thead');
      timeTableHeader.innerHTML = "<th colspan='3'>" + busStopArrivalInfo[0].stationName + "</th>";
      timetable?.appendChild(timeTableHeader);
      const timeTableBody = document.createElement('tbody');
      timetable?.appendChild(timeTableBody);
      busStopArrivalInfo.forEach((arrivalInfo) => {
        timeTableBody?.appendChild(createTD(arrivalInfo));
      });
    });
  }

  function updatePostcode(data: React.ChangeEvent<HTMLInputElement>): void {
    setPostcode(data.target.value)
  }

  return <>
    <div className="container-fluid centred">
    <h1> 🚌 BusBoard 🚌 </h1>
    <form action="" onSubmit={formHandler}>
      <label htmlFor="postcodeInput"> Postcode: </label>
      <input type="text" id="postcodeInput" onChange={updatePostcode}/>
      <input type="submit" value="Submit"/>
    </form>
    <div id="tableContainer"></div>
    </div>
    {populateBusTimetable()}
  </>;
}

export default App;